### PR TITLE
Main

### PR DESCRIPTION
**Pull request by vorvek**
Polytrack made reponsive-ish, except for the train sensors. I need to understand what's going on there first.

### CODE REVIEW

**Comment by vorvek** [comment]
Added polystructure to the pull request

**Comment by vorvek** [comment]
Added Polyaffinity to the pull request

**Comment by vorvek** [comment]
Added PolyNET to the pull request

**Comment by vorvek** [comment]
Added contact form to the pull request

**Comment by DylanHalstead** [comment]
The thought process behind polytrack was there are two containers:
The legend with the one red dot, this one would not really change
The next has the png of the train with the red dots acting as "sensors". The idea was to have the sensors flash (0 transparency to 100) while the train moves back and forth (to kinda give the illusion of a moving train)

This idea can be scratched if it's a bit difficult to have this working in a mobile friendly environment. The static image gets the point across fairly well.

Lmk if this makes sense and what you think is best

**Comment by vorvek** [comment]
We can create  a simple animated webp for that, I think. It should be 
quite small in size, considering the small changes between frames.

**Comment by DylanHalstead** [comment]
I've never dealt with webp files before but it seems like it will be
efficient to load as you said with its minimal changes to the original
image. With the image moving left to right would the file understand this
and save space or would the transparent pixel turning to a different color
be considered a whole new entity (I'm not sure if this makes sense. I'm
trying to say will this specific animation save a fair bit of space or will
it be better to just make the CSS animation by hand).

Let me know what you need from me,
Dylan Halstead

**Pull request merged**
